spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/shicgf?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

